name: API Tests with Newman

on:
  push:
    branches: [main]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests with Newman
        run: |
          newman run users.postman_collection.json \
            --iteration-data login_data.csv \
            --reporters cli
